services:
  cart-api:
    image: ${DOCKER_USERNAME}/e-tic-cart-api:latest
    container_name: cart-api-prod
    ports:
      - "4002:4002"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  home:
    image: ${DOCKER_USERNAME}/e-tic-home:latest
    container_name: home-app-prod
    ports:
      - "3000:3000"
    depends_on:
      - cart-api
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CART_API_URL=http://cart-api:4002
    restart: unless-stopped
    networks:
      - app-network

  cart:
    image: ${DOCKER_USERNAME}/e-tic-cart:latest
    container_name: cart-app-prod
    ports:
      - "3001:3001"
    depends_on:
      - cart-api
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CART_API_URL=http://cart-api:4002
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - home
      - cart
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 